name: "🐛 Bug Report"
description: "Report a bug to help us improve the modpack."
title: "[Bug] <short description>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out this form as clearly and completely as possible.
        This helps us identify and fix bugs faster. Thank you!

  - type: textarea
    id: bug-description
    attributes:
      label: "📝 Bug Description"
      description: "What happened? Describe the issue clearly and concisely."
      placeholder: "Example: When launching version x.x.x, the game crashes after the loading screen."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "🔁 Steps to Reproduce"
      description: "How can we recreate the issue? Use a numbered list."
      placeholder: |
        1. Open the launcher
        2. Select version x.x.x
        3. Click 'Play'
        4. Observe crash during loading
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "✅ Expected Behavior"
      description: "What did you expect to happen instead?"
      placeholder: "Example: The game loads normally and reaches the main menu."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: "❌ Actual Behavior (Optional)"
      description: "If different from above, describe what actually happened in more detail."

  - type: textarea
    id: screenshots
    attributes:
      label: "📷 Screenshots / Media (Optional)"
      description: "Drag and drop or paste screenshots or logs here."
      placeholder: "You can paste screenshots or upload logs here."

  - type: input
    id: modpack-version
    attributes:
      label: "🧪 Modpack Version"
      description: "Which version of the modpack were you using?"
      placeholder: "x.x.x"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: "💻 Operating System"
      multiple: true
      options:
        - Windows
        - macOS
        - Linux
        - Other (explain in 'Additional Context')
    validations:
      required: true

  - type: dropdown
    id: cpu
    attributes:
      label: "🧠 CPU Architecture"
      multiple: true
      options:
        - x86_64
        - arm64 (Apple Silicon)
        - armhf (32-bit ARM)
        - Intel processor
        - AMD processor
        - Apple CPU
        - I don't know
        - Other (explain in 'Additional Context')

  - type: dropdown
    id: gpu
    attributes:
      label: "🎮 Graphics Card (GPU)"
      multiple: true
      options:
        - NVIDIA
        - AMD
        - Intel
        - Apple GPU
        - No GPU
        - I don't know
        - Other (explain in 'Additional Context')

  - type: input
    id: crash-report
    attributes:
      label: "🧾 Crash Report (if available)"
      description: "Paste the link to your crash report (upload to https://mclo.gs)."
      placeholder: "Example: https://mclo.gs/abc123"

  - type: textarea
    id: additional-context
    attributes:
      label: "🧩 Additional Context (Optional)"
      description: "Include any other information that might help (RAM allocated, Java version, recent mod changes, etc.)."
