name: "🐛 Bug Report"
description: "Create a bug report to help us improve the modpack."
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe the bug"
      description: "Provide a clear and concise description of what the bug is."
      placeholder: "e.g. When I tried to launch version x.x.x, the game crashed."
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: "Steps to Reproduce"
      description: "Provide a numbered list of steps to reproduce the issue."
      placeholder: |
        1. Launch the game
        2. Click 'Play' on version x.x.x
        3. Observe the crash
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "Describe what you expected to happen."
      placeholder: "e.g. The game should launch and display the main menu."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "Upload any relevant screenshots (optional)."
      placeholder: "Attach files by dragging and dropping them here."

  - type: input
    id: version
    attributes:
      label: "Modpack Version"
      description: "Which version of the modpack were you using?"
      placeholder: "e.g. v1.2.3"
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: "Operating System(s)"
      description: "Select the OS you're using."
      multiple: true
      options:
        - Windows
        - macOS
        - Linux
        - Other (please describe in 'Additional Context')
    validations:
      required: true

  - type: dropdown
    id: cpu-architecture
    attributes:
      label: "CPU Architecture(s)"
      description: "Select your CPU architecture."
      multiple: true
      options:
        - I don't know
        - x86_64
        - arm64/aarch64
        - arm64 (Apple Silicon)
        - armhf/arm32
        - Intel processor
        - AMD processor
        - Apple CPU
        - Other (please describe in 'Additional Context')

  - type: dropdown
    id: gpu
    attributes:
      label: "GPU(s)"
      description: "Select your GPU or graphics solution."
      multiple: true
      options:
        - I don't know
        - No GPU
        - NVIDIA GPU
        - AMD GPU
        - Intel GPU
        - Other (please describe in 'Additional Context')

  - type: input
    id: crash-report
    attributes:
      label: "Relevant Crash Report"
      description: "If a crash report was generated, upload it to https://mclo.gs and paste the link here."

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any other context about the problem here."
      placeholder: "e.g. Java version, amount of allocated RAM, recent changes, etc."
