name: "✨ Feature Request"
description: "Suggest a new feature or improvement for the modpack."
title: "[Feature] <short description>"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve the modpack by suggesting features!
        Please choose the type of request and provide details. Thanks!

  - type: dropdown
    id: type-of-request
    attributes:
      label: "📌 Type of Request"
      description: "Is it a new mod suggestion or a configuration change?"
      options:
        - "New Mod"
        - "Config Change"
    validations:
      required: true

  - type: textarea
    id: new-mod-description
    attributes:
      label: "🧩 New Mod Suggestion"
      description: "Describe the mod you'd like to add, and why it's useful."
      placeholder: "Example: Add Xaero’s Minimap to help with navigation."
    validations:
      required: true
    when:
      id: type-of-request
      value: "New Mod"

  - type: textarea
    id: config-change-description
    attributes:
      label: "⚙️ Config Change Suggestion"
      description: "Describe the configuration change you propose and its benefits."
      placeholder: "Example: Enable vein mining for iron ore to improve early-game mining."
    validations:
      required: true
    when:
      id: type-of-request
      value: "Config Change"

  - type: dropdown
    id: modpack-version
    attributes:
      label: "🧪 Modpack Version"
      description: "Which version of the modpack are you referring to?"
      options:
        - Latest
        - Previous
        - Not version-specific
      default: 0
    validations:
      required: true
