name: "✨ Feature Request"
description: "Suggest a new mod or config change for the modpack."
title: "[Feature] <short description>"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve the modpack by suggesting features or improvements.
        Please select the type of request and fill in the matching section only.

  - type: dropdown
    id: type-of-request
    attributes:
      label: "📌 Type of Request"
      description: "Is it a new mod suggestion or a configuration change?"
      options:
        - New Mod
        - Config Change
    validations:
      required: true

  - type: textarea
    id: new-mod-description
    attributes:
      label: "🧩 New Mod Suggestion"
      description: "If you're suggesting a new mod, describe it and explain why you think it should be added. Leave this blank if not applicable."
      placeholder: "Example: Add Xaero’s Minimap to help with navigation."

  - type: textarea
    id: config-change-description
    attributes:
      label: "⚙️ Config Change Suggestion"
      description: "If you're suggesting a configuration change, explain the change and why it's helpful. Leave this blank if not applicable."
      placeholder: "Example: Enable keepInventory in config for easier exploration."

  - type: dropdown
    id: modpack-version
    attributes:
      label: "🧪 Modpack Version"
      description: "Which version of the modpack are you referring to?"
      options:
        - Latest
        - Previous
        - Not version-specific
      default: 0
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: "🔗 Additional Context (Optional)"
      description: "Links to mod pages, videos, or more info that help explain your request."
      placeholder: "Example: https://modrinth.com/mod/xaeros-minimap"
