name: OS Compatibility Ticket
description: Show an icompatible OS to be added to the list.
title: "[OS Compatibility Request] "
labels: [compatibility]
assignees: []

body:
  - type: input
    id: os-name
    attributes:
      label: Operating System Name
      description: Enter the full name and version of the operating system (e.g. Windows 10 22H2, Ubuntu 24.04, etc.)
    validations:
      required: true


  - type: input
    id: video
    attributes:
      label: Video Link 
      placeholder: you can also put a link
    validations:
      required: true

  - type: textarea
    id: anything-else
    attributes:
      label: Anything Else? (Optional)
      placeholder: Optional but helpful!
    validations:
      required: false
