name: OS Compatibility Request
description: Request compatibility check or support for a specific operating system.
title: "[OS Compatibility Request] "
labels: [compatibility]
assignees: []

body:
  - type: input
    id: os-name
    attributes:
      label: 🖥️ Operating System Name
      description: Enter the full name and version of the operating system (e.g. Windows 10 22H2, Ubuntu 24.04, etc.)
      placeholder: e.g. Fedora 40 Workstation
    validations:
      required: true


  - type: input
    id: video
    attributes:
      label: 📹 Video Link 
      placeholder: e.g. https://youtu.be/example
    validations:
      required: true

  - type: textarea
    id: anything-else
    attributes:
      label: 💬 Anything Else? (Optional)
      description: Add any other notes, suggestions, or logs you’d like to share.
      placeholder: Optional but helpful!
    validations:
      required: false
