name: Version request
description: request a version for the modpack
title: "[OS Compatibility Request] "
labels: [compatibility]
assignees: []

body:

  - type: input
    id: version
    attributes:
      label: Version
    validations:
      required: true
